apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: week-11-php-app
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: week-11-php-app
  template:
    metadata:
      labels:
        app: week-11-php-app
    spec:
      containers:
      - image: us.gcr.io/cloud-tech-week-11/cloud-tech:v1
        imagePullPolicy: Always
        name: week-11-php-app
        resources:
          requests:
            cpu: 100m
            memory: 400m
        env:
          - name: MYSQL_USER
            valueFrom:
              # referenced from kubernetes secrets
              secretKeyRef:
                name: mysql-credentials
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: MYSQL_HOST
            value: mysql.default.svc.cluster.local
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  # the name web here means you can reference the PHP pods
  # using the host web.default.svc.cluster.local from within the cluster
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: week-11-php-app
  type: LoadBalancer