apiVersion: v1
kind: Service
metadata:
  name: mysql_db
  labels:
    app: mysql_db
spec:
  ports:
    - port: 3306
  selector:
    app: mysql_db
    tier: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql_db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysqldb-mysql
  labels:
    app: mysql_db
spec:
  selector:
    matchLabels:
      app: mysql_db
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql_db
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE MyGuests( 
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(30),
    lastname VARCHAR(30)
    );

    INSERT INTO MyGuests 
        (id,firstname,lastname) 
    VALUES 
        (1,"Madhavi","Rao"),
        (2,"Eric","Peterson"),
        (3,"Steve","Dodd");
