apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php_web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php_web
      tier: frontend
  template:
    metadata:
      labels:
        app: php_web
        tier: frontend
    spec:
      containers:
      - image: php-app:cloud-tech
        name: php_web
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        env:
          - name: SQL_HOST
            value: mysql_db   #Same as the one in mysql-deploy.yml
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php_web
  labels:
    app: php_web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: php_web
    tier: frontend
    type: LoadBalancer