apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    app: webserver
type: Opaque
data:
  # root password for MySQL
  # the actual password is root
  # echo -n root | base64
  rootpw: cm9vdA==
  # user for MySQL
  # the actual username is master
  # echo -n master | base64
  user: bWFzdGVy
  # password for the second MySQL user
  # the actual password is mastersql
  # echo -n mastersql | base64
  password: bWFzdGVyc3Fs
  # password for the second MySQL user
  # the actual password is mastersql
  # echo -n mydb | base64
  db: bXlkYg== 
