apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: firstapp
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
  selector:
    app: firstapp

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firstapp
  template:
    metadata:
      labels: 
        app: firstapp
    spec:
          containers:
          - name: hello-ctr
            image: nginx-mongod
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80
