apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 15043
      protocol: TCP
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels: 
        app: app
    spec:
       containers:
       - name: nginx
         image: nginx_webserver
         imagePullPolicy: IfNotPresent
         ports:
         - containerPort: 80
           name: nginx
         env:
           - name: MYSQL_USER
             value: admin
           - name: MYSQL_PASSWORD
             value: secret
           - name: MYSQL_DATABASE
             value: classes
           - name: MYSQL_HOST
             value: mysql
