apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: phpapp
 labels:
  app: phpapp
spec:
 template:
  metadata:
   labels:
    app: phpapp
  spec:
   containers:
   - name: phpapp
     image: myimage
     imagePullPolicy: Never
     name: phpapp
     env:
     - name: MYSQL_USER
       value: shikha
     - name: MYSQL_PASSWORD
       value: secret
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: web
spec:
 ports:
 - port: 80
   protocol: TCP
 selector:
   app: phpapp
